name: "💡 Feature Request (English)"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Describe your idea as detailed as possible.
        
  - type: dropdown
    id: type
    attributes:
      label: Type of Suggestion
      options:
        - Gameplay Improvement
        - Performance Optimization
        - New Configuration
        - Quality of Life (QoL)
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
      placeholder: Describe your idea in detail...
    validations:
      required: true
      
  - type: textarea
    id: reason
    attributes:
      label: Why is this useful?
      description: Explain why this change would benefit the modpack
      placeholder: What problem does this solve? Or what improvement does it bring?
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you thought about alternative solutions?
      placeholder: Are there other ways to achieve this?
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other info, screenshots or links
      placeholder: Anything else that might be relevant...
