name: "📦 Mod Request (English)"
description: Suggest a new mod for the modpack
title: "[Mod]: "
labels: ["mod-request"]
body:
  - type: markdown
    attributes:
      value: |
        Want to see a mod added to the modpack? Fill out the form!
        
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: What is the mod called?
      placeholder: e.g. Applied Energistics 2
    validations:
      required: true
      
  - type: input
    id: mod-link
    attributes:
      label: Link to Mod
      description: CurseForge or Modrinth link
      placeholder: https://www.curseforge.com/minecraft/mc-mods/...
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: What does the mod do?
      description: Briefly describe what the mod adds
      placeholder: The mod adds...
    validations:
      required: true
      
  - type: textarea
    id: reason
    attributes:
      label: Why should it be added?
      description: Why does this mod fit the modpack?
      placeholder: This mod would fit well because...
    validations:
      required: true
      
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which category does the mod fall into?
      options:
        - Tech / Technology
        - Magic
        - Decoration / Building
        - Adventure / Exploration
        - Agriculture / Farming
        - Performance
        - Quality of Life
        - Other
    validations:
      required: true
      
  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility
      options:
        - label: I have verified that the mod is compatible with Forge 1.20.1
          required: true
        - label: The mod hasn't been suggested yet
          required: true
        - label: I have checked for conflicts with existing mods
          required: false
